### ISSUE TITLE
Create documentation either video or written to add credit to RapidPro

### ISSUE THREAD

**Issue by msschroeder** [onaio/support#199]
Create documentation either video or written to add credit to RapidPro

Steps to add credits:
1. Log in as super user
2. Find the organization name (you should have this confirmed before starting the process - It also helps to know who the owner is (email))
3. Click the name 
4. Should ask if you want to service
5. Click top-ups
6. Add the required number of credits (note - They expire after 1 year). Nothing else in this window is required
7. Should now show.

**Comment by eochieng-lab** [comment]
@msschroeder , this is complete. Link to documentation can be accessed [here](https://docs.google.com/document/d/1cJJCqdS2pIsOWurIBUK3o49cJJh3Q8s9vy7M5krAKQY/edit?usp=sharing).
