### ISSUE TITLE
OMK/ODK integration

### ISSUE THREAD

**Issue by Janemesi** [onaio/support#200]
- Initially one was able to edit the OSM features when they downloaded ODK Collect and OMK (Ona version) on their android devices. For more information on how to, take a look at this [guide](https://help.ona.io/knowledge-base/how-to-use-openstreetmaps-in-openmapkit/). However, with the android updates that were done mid-last year, it seems like the integration is no longer supported. More details can be found in this [thread](https://forum.getodk.org/t/odk-collect-crashing-on-tecno-sas6-after-only-one-or-two-interviews/23357/13)
- Right now the points are not loading when you add the osm file to the OMK folder within your android device
Hence:
1. Should we unpublish the OSM documentation within our help site?
2. Should we reach out to the OMK team for further assistance on how to make it work?

**Comment by msschroeder** [comment]
I have unpublished the documentation
